name: "CI (Integração Continua): Main workflow"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # This workflow contains a single job called "build"
  linter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run installation
        run: npm i
      - name: Run linter
        run: npm run lint
